{{- if .Values.sealedSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hatchet-db-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
{{- range $key, $value := .Values.sealedSecret.encryptedData }}
    {{ $key }}: {{ $value }}
{{- end }}
  template:
    metadata:
      name: hatchet-db-secret
      namespace: {{ .Release.Namespace }}
{{- end }}
