apiVersion: v2
name: hatchet-api
description: A Helm chart for deploying Hatchet API components on Kubernetes.
type: application
version: 0.71.0
maintainers:
  - name: Hatchet Engineering
    email: alexander@hatchet.run
