{{- if .Values.caddy.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: hatchet-caddy-config
  labels:
{{- include "hatchet.labels" . | nindent 4 }}
{{- if .Values.caddy.annotations }}
  annotations:
{{ toYaml .Values.caddy.annotations | indent 4 }}
{{- end }}
data:
  Caddyfile: |
    http://localhost:8080 {
        handle /api/* {
            reverse_proxy {{ .Release.Name }}-api:8080
        }

        handle /* {
            reverse_proxy {{ .Release.Name }}-frontend:8080
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-caddy
  labels:
{{- include "hatchet.labels" . | nindent 4 }}
{{- if .Values.caddy.annotations }}
  annotations:
{{ toYaml .Values.caddy.annotations | indent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
      - name: caddy
        image: "{{ .Values.caddy.image.repository }}:{{ required "Please set a value for .Values.image.tag" .Values.caddy.image.tag }}"
        imagePullPolicy: {{ .Values.caddy.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: caddyfile-volume
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
      volumes:
      - name: caddyfile-volume
        configMap:
          name: hatchet-caddy-config
---
apiVersion: v1
kind: Service
metadata:
  name: caddy
  labels:
{{- include "hatchet.labels" . | nindent 4 }}
{{- if .Values.caddy.annotations }}
  annotations:
{{ toYaml .Values.caddy.annotations | indent 4 }}
{{- end }}

spec:
  selector:
    app: caddy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
{{- end -}}