{{- if .Values.setupJob.enabled }}
# create a role and rolebinding to write to the configmap
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "hatchet.fullname" . }}
  labels:
{{- include "hatchet.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "hatchet.fullname" . }}
  labels:
{{- include "hatchet.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "hatchet.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "hatchet.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name | trunc 20 }}-{{ randAlphaNum 10 | lower }}"
  labels:
{{- include "hatchet.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 900
  template:
    metadata:
      name: {{ template "hatchet.fullname" . }}-migration
      labels:
{{- include "hatchet.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      shareProcessNamespace: true
      serviceAccountName: {{ template "hatchet.serviceAccountName" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      initContainers:
      {{- if .Values.migrationJob.enabled }}
      - name: check-db-connection
        image: "{{ .Values.postgresImage.repository }}:{{ required "Please set a value for .Values.postgresImage.tag" .Values.postgresImage.tag }}"
        imagePullPolicy: {{ .Values.postgresImage.pullPolicy }}
        command: ['/bin/sh','-lc']
        args:
          - |
            until pg_isready -q -t 5 -d "$DATABASE_URL"; do
              echo "waiting for database"; sleep 2
            done
            psql "$DATABASE_URL" -c "SELECT 1"
        env:
      {{- range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
      {{- end }}
        envFrom:
{{ toYaml .Values.envFrom | indent 10 }}

      # Run migrations as an initContainer
      - name: migration-job
        image: "{{ .Values.migrationJob.image.repository }}:{{ required "Please set a value for .Values.image.tag" (coalesce .Values.sharedConfig.image.tag .Values.migrationJob.image.tag) }}"
        imagePullPolicy: {{ .Values.migrationJob.image.pullPolicy }}
        securityContext:
          capabilities:
            add:
              - SYS_PTRACE
        env:
        {{- range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
        {{- end }}
        {{- if .Values.envFrom }}
        envFrom:
{{ toYaml .Values.envFrom | indent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.seedJob.enabled }}
      - name: seed-job
        image: "{{ .Values.seedJob.image.repository }}:{{ required "Please set a value for .Values.image.tag" (coalesce .Values.sharedConfig.image.tag .Values.seedJob.image.tag) }}"
        imagePullPolicy: {{ .Values.seedJob.image.pullPolicy }}
        # this command requires read-write access on the hatchet-config configmap
        command: ["/hatchet/hatchet-admin", "quickstart", "--skip", "certs", "--skip", "keys"]
        securityContext:
          capabilities:
            add:
              - SYS_PTRACE
        env:
          - name: SERVER_DEFAULT_ENGINE_VERSION
            value: "V1"
        {{- range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
        {{- end }}
        {{- if .Values.envFrom }}
        envFrom:
{{ toYaml .Values.envFrom | indent 10 }}
        {{- end }}
      {{- end }}
      {{- if and (not .Values.migrationJob.enabled) (not .Values.seedJob.enabled) }}
      []
      {{- end }}
      containers:
{{- if .Values.quickstartJob.enabled }}
      - name: setup-job
        image: "{{ .Values.setupJob.image.repository }}:{{ required "Please set a value for .Values.image.tag" (coalesce .Values.sharedConfig.image.tag .Values.setupJob.image.tag) }}"
        imagePullPolicy: {{ .Values.setupJob.image.pullPolicy }}
        # this command requires read-write access on the hatchet-config configmap
        command: ["/hatchet/hatchet-admin", "k8s", "quickstart", "--namespace", "{{ .Release.Namespace }}", "--overwrite=false"]
        securityContext:
          capabilities:
            add:
              - SYS_PTRACE
        env:
        {{- range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
        {{- end }}
        {{- if .Values.envFrom }}
        envFrom:
{{ toYaml .Values.envFrom | indent 10 }}
        {{- end }}
{{- else }}
      # Write an empty container to avoid a syntax error
      - name: empty
        image: "alpine:3.14"
        command: ["sh", "-c", "echo 'No setup job configured'"]
{{- end }}
---
{{- if .Values.workerTokenJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name | trunc 20 }}-{{ randAlphaNum 10 | lower }}-worker-token"
  labels:
{{- include "hatchet.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 900
  template:
    metadata:
      name: {{ template "hatchet.fullname" . }}-migration
      labels:
{{- include "hatchet.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      shareProcessNamespace: true
      serviceAccountName: {{ template "hatchet.serviceAccountName" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      initContainers:
      - name: check-db-connection
        image: "{{ .Values.postgresImage.repository }}:{{ required "Please set a value for .Values.postgresImage.tag" .Values.postgresImage.tag }}"
        imagePullPolicy: {{ .Values.postgresImage.pullPolicy }}
        command: ['sh','-lc']
        args:
          - |
            until pg_isready -q -t 5 -d "$DATABASE_URL"; do
              echo "waiting for database"; sleep 2
            done
        env:
        {{- range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
        {{- end }}
        envFrom:
{{ toYaml .Values.deploymentEnvFrom | nindent 10 }}
{{- if .Values.envFrom }}
{{ toYaml .Values.envFrom | nindent 10 }}
{{- end }}
      containers:
      - name: setup-worker-token
        image: "{{ .Values.setupJob.image.repository }}:{{ required "Please set a value for .Values.image.tag" (coalesce .Values.sharedConfig.image.tag .Values.setupJob.image.tag) }}"
        imagePullPolicy: {{ .Values.setupJob.image.pullPolicy }}
        # this command requires read-write access on the hatchet-config configmap
        command: ["/hatchet/hatchet-admin", "k8s", "create-worker-token", "--namespace", "{{ .Release.Namespace }}"]
        securityContext:
          capabilities:
            add:
              - SYS_PTRACE
        env:
        {{- range $key, $value := .Values.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
        {{- end }}
        envFrom:
{{ toYaml .Values.deploymentEnvFrom | nindent 10 }}
{{- if .Values.envFrom }}
{{ toYaml .Values.envFrom | nindent 10 }}
{{- end }}
{{- end }}
{{- end }}
