apiVersion: v2
name: hatchet-frontend
description: A Helm chart for deploying a frontend static file server on Kubernetes.
type: application
version: 0.2.0
maintainers:
  - name: Hatchet Engineering
    email: alexander@hatchet.run
